<a href="https://colab.research.google.com/github/sowmR/pythonSamples/blob/main/Matrix_Processing_in_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [8]:
m1 = [[1,2,3],[3,4,5]]
m2 = [[2,5],[2,3]]
m3 = [[3,7,2],[9,14,2]]

### Arithmetic operations

For the Arithmetic operations both matrix/array should be of same shape.

Trying to perform arithmetic operation between two matrix of different shape will return error.
Example: adding 2x3 matrix with 2x2 matrix will return error.


In [12]:
# Matrix addition 
m4 = np.add(m1,m3)
print(m4)

[[ 4  9  5]
 [12 18  7]]


In [10]:
# Matrix Subtraction
m4 = np.subtract(m1,m3)
m4

array([[ -2,  -5,   1],
       [ -6, -10,   3]])

In [13]:
# matrix Multiplication
print(np.multiply(m1,m3))


[[ 3 14  6]
 [27 56 10]]


In [15]:
# trying to multiply two different matrix size
print(np.multiply(m1,m2))

ValueError: ignored