<a href="https://colab.research.google.com/github/sowmR/pythonSamples/blob/main/Matrix_Processing_in_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
m1 = [[1,2,3],[3,4,5]]
m2 = [[2,5],[2,3]]
m3 = [[3,7,2],[9,14,2]]

### Arithmetic operations

For the Arithmetic operations both matrix/array should be of same shape.

Trying to perform arithmetic operation between two matrix of different shape will return error.
Example: adding 2x3 matrix with 2x2 matrix will return error.


In [ ]:
# Matrix addition 
m4 = np.add(m1,m3)
print(m4)

[[ 4  9  5]
 [12 18  7]]


In [ ]:
# Matrix Subtraction
m4 = np.subtract(m1,m3)
m4

array([[ -2,  -5,   1],
       [ -6, -10,   3]])

In [ ]:
# matrix Multiplication
print(np.multiply(m1,m3))


[[ 3 14  6]
 [27 56 10]]


In [ ]:
# trying to multiply two different matrix size.  When multiplying aXb with cXd matrix, it is important that b=c. Otherwise it will throw error
print(np.multiply(m1,m2))

ValueError: ignored

### Difference between np.multiply and dot product

m1 = 
      
      [a b

      c d]

m2 = 
      
      [e f

      g h]


np.multiply(m1,m2) => 
   
                      [a*e  b*f
    
                       c*g   d*h]

m1.dot(m2) => 

            [a*e+b*g    a*f+b*h

             c*e+c*g    c*f+c*h]




In [ ]:
m1 = [[2,3],[3,1]]
m2 = [[1,3],[4,5]]
print(np.multiply(m1,m2))
print(np.array(m1).dot(np.array(m2)))

[[ 2  9]
 [12  5]]
[[14 21]
 [ 7 14]]


In [ ]:
# matmul is same as dot product
np.matmul(m1,m2)

array([[14, 21],
       [ 7, 14]])

### hstack, vstack

**Note**: 

- hstack between two matrix should have same number of rows
- vstack between two matrix should have same number of columns


In [ ]:
a = [1,2,3]
b = [4,5,6]
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
a = [[1,2],[2,3]]
b = [[4,5],[5,6]]
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[[1 2 4 5]
 [2 3 5 6]]
[[1 2]
 [2 3]
 [4 5]
 [5 6]]


In [ ]:
a = [[1,2],[2,3]]
b = [4,5]

print(np.vstack((a,b)))
print(np.hstack((a,b))) # will throw error 

[[1 2]
 [2 3]
 [4 5]]


ValueError: ignored

In [ ]:
a = [[1,2],[2,3]]
b = [[4],[5]]

print(np.hstack((a,b)))
print(np.vstack((a,b))) # will throw error 

[[1 2 4]
 [2 3 5]]


ValueError: ignored

In [ ]:
a = [
     [1.171875, 0.,       0.      ],
     [0.,       1.171875, 0.      ],
     [0.,       0.,       3.      ]
    ]
b = [
     [ -300.],
     [ -225.],
     [-1097.]
     ]
hs = np.hstack((a,b))
print(hs)
vs = np.vstack((hs,[0,0,0,1]))
print(vs)
print(vs.shape)

[[    1.171875     0.           0.        -300.      ]
 [    0.           1.171875     0.        -225.      ]
 [    0.           0.           3.       -1097.      ]]
[[ 1.171875e+00  0.000000e+00  0.000000e+00 -3.000000e+02]
 [ 0.000000e+00  1.171875e+00  0.000000e+00 -2.250000e+02]
 [ 0.000000e+00  0.000000e+00  3.000000e+00 -1.097000e+03]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]
(4, 4)


### Linear algebra

In [ ]:
a= [[1., 2.], [3., 4.]]
print(a)
print(np.transpose(a))
print(np.linalg.inv(a))

[[1.0, 2.0], [3.0, 4.0]]
[[1. 3.]
 [2. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]


### Statistics

In [3]:
a = [
     [2,4,65,2],
     [12,41,6,5],
     [20,23,5,8],
     [20,23,15,3]
]

a1 = [2,4,65,2,12,41,6,5,20,23,5,8,20,23,15,3]

print(np.percentile(a,95),np.quantile(a,0.95))
print(np.percentile(a1,95),np.quantile(a1,0.95))
print(np.amax(a), np.amax(a1))

47.0 47.0
47.0 47.0
65 65
