<a href="https://colab.research.google.com/github/sowmR/pythonSamples/blob/main/Python_codeSamples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = [[
            [0,0,1,0],
            [1,0,1,0],
            [0,0,1,0],
            [0,0,0,1]
        ],
        [
            [0,0,1,0],
            [1,0,1,1],
            [0,0,1,0],
            [1,0,0,1]
        ],
        [
            [0,0,1,0],
            [1,0,1,0],
            [0,1,1,0],
            [1,0,0,1]
        ]]
arr = np.array(arr)
print(arr.shape)
print(np.percentile(arr,0.5))

(3, 4, 4)
0.0


## Signed Integer Vs Unsigned Integer

A signed integer is 32 bit integer in the range of -(2^31) to (2^31)  which contains both positive and negative number. 

An unsigned integer is a 32 bit non-negative integer in the range of 0 to (2^32)-1


In [2]:
# convert signed integer to unsigned integer
signed_integer = np.int16(-100)

# method -1 
# Adding 2^16  as this will be 16 bit integer to convert signed to unsigned integer
unsigned_integer = signed_integer+2**16
print(unsigned_integer)
print(type(unsigned_integer))

# method - 2
# Adding 1<<16 to convert signed to 
# unsigned integer
unsigned_integer = signed_integer+(1 << 16)
print(unsigned_integer)

65436
<class 'numpy.int64'>
65436


## Image processing sample

In [4]:
imArr = [[ 0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0 ,107 ,114 ,121 ,130 ,134 ,136 ,142 ,144 ,149 ,150 ,152 ,154 ,156
  ,158 ,159 ,160 ,161 ,162 ,163 ,164 ,164 ,165 ,166 ,167 ,167 ,168 ,169 ,170 ,170 ,171 ,172
  ,173 ,174 ,175 ,176 ,177 ,178 ,179 ,180 ,180 ,181 ,182 ,183 ,184 ,185 ,186 ,186 ,187 ,187
  ,188 ,188 ,189 ,189 ,190 ,190 ,191 ,191 ,192 ,192 ,192 ,192 ,192 ,192 ,192 ,192 ,193 ,193
  ,194 ,194 ,194 ,194 ,195 ,195 ,195 ,195 ,195 ,195 ,194 ,194 ,194 ,194 ,194 ,193 ,193 ,192
  ,192 ,191 ,191 ,191 ,191 ,191 ,191 ,191 ,191 ,190 ,190 ,190 ,189 ,188 ,188 ,188 ,187 ,187
  ,186 ,186 ,185 ,185 ,184 ,183 ,183 ,182 ,182 ,181 ,180 ,179 ,179 ,178 ,177 ,176 ,176 ,175
  ,174 ,174 ,173 ,172 ,172 ,171 ,171 ,170 ,169 ,168 ,167 ,166 ,165 ,164 ,163 ,163 ,162 ,162
  ,161 ,161 ,160 ,160 ,159 ,159 ,158 ,158 ,157 ,156 ,156 ,155 ,155 ,154 ,154 ,153 ,153 ,152
  ,152 ,152 ,151 ,150 ,150 ,150 ,149 ,149 ,148 ,148 ,148 ,147 ,147 ,146 ,145 ,145 ,144 ,143
  ,141 ,139 ,135  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0],
   
   [ 0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0 ,107 ,114 ,119 ,126 ,134 ,134 ,142 ,143 ,149 ,150 ,152 ,153 ,155
  ,157 ,158 ,159 ,161 ,162 ,163 ,164 ,164 ,165 ,166 ,167 ,168 ,168 ,169 ,169 ,170 ,172 ,172
  ,173 ,174 ,175 ,175 ,176 ,178 ,179 ,180 ,180 ,181 ,181 ,182 ,183 ,184 ,185 ,185 ,186 ,187
  ,187 ,188 ,188 ,189 ,189 ,189 ,190 ,190 ,191 ,191 ,191 ,191 ,192 ,192 ,192 ,192 ,192 ,192
  ,192 ,193 ,193 ,193 ,194 ,194 ,194 ,194 ,194 ,194 ,194 ,194 ,194 ,193 ,193 ,193 ,192 ,192
  ,192 ,191 ,191 ,190 ,191 ,190 ,190 ,190 ,190 ,190 ,189 ,188 ,188 ,187 ,187 ,186 ,186 ,186
  ,185 ,185 ,184 ,184 ,183 ,183 ,182 ,182 ,181 ,180 ,180 ,179 ,178 ,177 ,176 ,175 ,174 ,174
  ,173 ,173 ,172 ,172 ,171 ,171 ,170 ,169 ,168 ,167 ,166 ,165 ,164 ,163 ,162 ,161 ,161 ,161
  ,160 ,160 ,159 ,159 ,158 ,158 ,158 ,157 ,157 ,156 ,156 ,155 ,155 ,154 ,154 ,153 ,153 ,152
  ,152 ,151 ,151 ,150 ,150 ,149 ,149 ,149 ,148 ,148 ,147 ,147 ,146 ,146 ,145 ,144 ,143 ,143
  ,142 ,139 ,136 ,133  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0
   ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0]
   ]

In [5]:
# changing the opacity of the image 

opacity = 0.8
imArr = np.array(imArr)
indx = imArr>0
nArr = imArr
nArr[indx] = np.subtract(255 ,np.multiply(opacity,np.subtract(255,imArr[indx])))
img_rgb = np.uint8(np.stack((nArr,)*3,axis=-1))
print(img_rgb[0][244:255])

[[204 204 204]
 [204 204 204]
 [204 204 204]
 [204 204 204]
 [204 204 204]
 [204 204 204]
 [205 205 205]
 [205 205 205]
 [206 206 206]
 [206 206 206]
 [206 206 206]]


# Matrix Processing

In [6]:
m1 = [[1,2,3],[3,4,5]]
m2 = [[2,5],[2,3]]

# addition
m3 = np.subtract(2,m1)
m3
imArr = np.array(m1)
indx = imArr>0
img_with_opacity = imArr
img_with_opacity[indx] = np.subtract(255 ,np.multiply(opacity,np.subtract(255,imArr[indx])))
print(img_with_opacity)

[[51 52 53]
 [53 54 55]]
